baseConfig:
  cuda: True
  do_train: True
  log_step: 1000
  save_step: 10000
  valid_step: 10000

complex_01:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 500
  lr: 0.0005
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 10000
  reg_weight: 0.01
  conf_neg_weight: 0.5
  vio_neg_weight: 1
  cl_nsize: 100
  cl_temp : 1.0
  data_reverse: False


complex_03:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 500
  lr: 0.0005
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 10000
  reg_weight: 0.05
  conf_neg_weight: 1
  cl_temp : 1.0
  vio_neg_weight: 1
  cl_nsize: 100
  data_reverse: False

complex_02:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 20
  dim: 500
  lr: 0.0005
  decay: 0.1
  max_step: 200003
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.000005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  data_reverse: False

complex_05:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 20
  dim: 500
  lr: 0.0005
  decay: 0.1
  max_step: 200003
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.000005
  conf_neg_weight: 0.1
  vio_neg_weight: 0.1
  cl_nsize: 200
  data_reverse: False

complex_06:
  batch_size: 2
  name: ComplEx
  dataset: YAGO
  gamma: 20
  dim: 500
  lr: 0.001
  decay: 0.1
  max_step: 200004
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.000005
  conf_neg_weight: 0.01
  vio_neg_weight: 0.01
  cl_nsize: 200
  data_reverse: False


complex_07:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 500
  lr: 0.0005
  decay: 0.1
  max_step: 200003
  n_size: 400
  test_step: 20000
  cl_temp : 0.1
  reg_weight: 0.000005
  conf_neg_weight: 0.1
  vio_neg_weight: 0.1
  cl_nsize: 200
  data_reverse: False

# 用于一层的
complex_04:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 20
  dim: 500
  lr: 0.0005
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.000005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  data_reverse: False

complex_03:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 500
  lr: 0.0001
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.000005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  data_reverse: False

hyper_graph:
  batch_size: 512
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.005
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 2
  data_reverse: False

hyper_graph_01:
  batch_size: 512
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.0005
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.000005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 2
  data_reverse: False

hyper_graph_02:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.01
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.000005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 2
  data_reverse: False

hyper_graph_mlp_l3_01:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.001
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.000005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 2
  data_reverse: False

hyper_graph_mlp_l3_02:
  batch_size: 256
  name: ComplEx
  dataset: FB15-237
  gamma: 200
  dim: 500
  lr: 0.001
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False

hyper_graph_mlp_l3_03:
  batch_size: 256
  name: ComplEx
  dataset: FB15-237
  gamma: 200
  dim: 500
  lr: 0.001
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.0000005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False

hyper_graph_n3_01:
  batch_size: 512
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.005
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False

hyper_graph_n3_011:
  batch_size: 512
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.0005
  decay: 0.1
  max_step: 300001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 2
  data_reverse: False

hyper_graph_n3_012:
  batch_size: 512
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.005
  decay: 0.1
  max_step: 300001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False

hyper_graph_n3_013:
  batch_size: 512
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.005
  decay: 0.1
  max_step: 400001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False

hyper_graph_n3_02:
  batch_size: 512
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.005
  decay: 0.1
  max_step: 300001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 2
  data_reverse: False

hyper_graph_n3_03:
  batch_size: 8
  name: ComplEx
  dataset: FB15-237
  gamma: 200
  dim: 500
  lr: 0.000001
  decay: 0.1
  max_step: 300001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 2
  data_reverse: False

hyper_graph_n3_04:
  batch_size: 512
  name: ComplEx
  dataset: FB15-237
  gamma: 200
  dim: 500
  lr: 0.0005
  decay: 0.1
  max_step: 300001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.0001
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 2
  data_reverse: False

hyper_graph_n3_05:
  batch_size: 256
  name: ComplEx
  dataset: FB15-237
  gamma: 200
  dim: 500
  lr: 0.0001
  decay: 0.1
  max_step: 300001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.000001
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 2
  data_reverse: False

hyper_edge_01:
  batch_size: 512
  name: ComplEx
  dataset: FB15-237
  gamma: 200
  dim: 500
  lr: 0.0001
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 0.5
  reg_weight: 0.0001
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False

hyper_edge_02:
  batch_size: 512
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 500
  lr: 0.0001
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 0.5
  reg_weight: 0.0001
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False

complex_soft_plus:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.001
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False

complex_soft_plus_lr:
  batch_size: 1024
  name: ComplEx
  dataset: YAGO
  gamma: 200
  dim: 1000
  lr: 0.0005
  decay: 0.1
  max_step: 200001
  n_size: 400
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00005
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False


hyper_graph_n3_15k:
  batch_size: 512
  name: ComplEx
  dataset: FB15-237
  gamma: 200
  dim: 1000
  lr: 0.001
  decay: 0.1
  max_step: 200001
  n_size: 256
  test_step: 20000
  cl_temp : 1.0
  reg_weight: 0.00001
  conf_neg_weight: 1
  vio_neg_weight: 1
  cl_nsize: 200
  layer: 1
  data_reverse: False