baseConfig: 
  cuda: True
  do_train: True
  og_step: 1000
  save_step: 10000
  valid_step: 10000


cl_0220_01: 
  batch_size: 4096
  name: ComplEx
  gamma: 1
  dim: 500
  lr: 0.001
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 20
  test_step: 50
  reg_weight: 0.1
  cl_weight: 0.00001
  margin: 0.2
  dropout: 0.1
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [40,15]
  test_neibor_size: [30,10]
  data_reverse: False


cl_0220_02: 
  batch_size: 4096
  name: ComplEx
  gamma: 1
  dim: 500
  lr: 0.001
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 20
  test_step: 50
  reg_weight: 0.1
  dropout: 0.5
  cl_weight: 0.00001
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False

cl_0220_03: 
  batch_size: 4096
  name: ComplEx
  gamma: 1
  dim: 500
  lr: 0.001
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 20
  test_step: 50
  reg_weight: 0.1
  cl_weight: 0.00001
  margin: 0.2
  dropout: 0.8
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [40,15]
  test_neibor_size: [30,10]
  data_reverse: False


cl_0220_04: 
  batch_size: 4096
  name: ComplEx
  gamma: 1
  dim: 500
  lr: 0.001
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 20
  test_step: 50
  reg_weight: 0.1
  dropout: 0.3
  cl_weight: 0.00001
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False


cl_0221_01: 
  batch_size: 4096
  name: ComplEx
  gamma: 1
  dim: 500
  lr: 0.005
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 20
  test_step: 50
  reg_weight: 0.1
  cl_weight: 0.00001
  margin: 0.2
  dropout: 0.1
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [40,15]
  test_neibor_size: [30,10]
  data_reverse: False


cl_0221_02: 
  batch_size: 4096
  name: ComplEx
  gamma: 1
  dim: 500
  lr: 0.01
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 20
  test_step: 50
  reg_weight: 0.1
  dropout: 0.5
  cl_weight: 0.00001
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False

cl_0221_03: 
  batch_size: 4096
  name: ComplEx
  gamma: 1
  dim: 500
  lr: 0.0005
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 20
  test_step: 50
  reg_weight: 0.1
  cl_weight: 0.00001
  margin: 0.2
  dropout: 0.8
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [40,15]
  test_neibor_size: [30,10]
  data_reverse: False


cl_0221_04: 
  batch_size: 4096
  name: ComplEx
  gamma: 1
  dim: 500
  lr: 0.0001
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 20
  test_step: 50
  reg_weight: 0.1
  dropout: 0.3
  cl_weight: 0.00001
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False