baseConfig: 
  cuda: True
  do_train: True
  og_step: 1000
  save_step: 10000
  valid_step: 10000

237_base_01: 
  batch_size: 512
  name: ComplEx
  dataset: FB15k-237
  gamma: 200
  dim: 100
  lr: 0.0005
  decay: 0.1
  max_step: 200000
  layer: 2
  n_size: 100
  test_step: 100
  reg_weight: 0.00005
  conf_neg_weight: 0.5
  vio_neg_weight: 1
  cl_nsize: 100
  margin: 0.2
  cl_temp: 1.0
  data_reverse: False

237_base_02: 
  batch_size: 128
  name: ComplEx
  dataset: FB15k-237
  gamma: 100
  dim: 100
  lr: 0.0001
  decay: 0.1
  max_step: 200000
  layer: 2
  n_size: 100
  test_step: 100
  reg_weight: 0.00005
  conf_neg_weight: 0.5
  vio_neg_weight: 1
  cl_nsize: 100
  margin: 0.2
  cl_temp: 1.0
  data_reverse: False

inductive_base_01: 
  batch_size: 1024
  name: ComplEx
  dataset: 237-v1
  gamma: 100
  dim: 100
  lr: 0.0001
  decay: 0.1
  max_step: 200000
  layer: 2
  n_size: 100
  test_step: 100
  reg_weight: 0.00005
  conf_neg_weight: 0.5
  vio_neg_weight: 1
  cl_nsize: 100
  margin: 0.2
  cl_temp: 1.0
  data_reverse: False

wn18rr_base_01: 
  batch_size: 1024
  name: ComplEx
  dataset: wn18rr
  gamma: 10
  dim: 100
  lr: 0.0005
  decay: 0.1
  max_step: 200000
  layer: 2
  n_size: 200
  test_step: 100
  reg_weight: 0.00005
  conf_neg_weight: 0.5
  vio_neg_weight: 1
  cl_nsize: 100
  margin: 0.2
  cl_temp: 1.0
  data_reverse: False

wn18rr_base_02: 
  batch_size: 1024
  name: ComplEx
  dataset: wn18rr
  gamma: 1
  dim: 200
  lr: 0.0005
  decay: 0.1
  max_step: 200000
  layer: 2
  n_size: 200
  test_step: 100
  reg_weight: 0.00005
  conf_neg_weight: 0.5
  vio_neg_weight: 1
  cl_nsize: 100
  margin: 0.2
  cl_temp: 1.0
  data_reverse: False


HyperKGEConfig: 
  dropout: 0.2
  num_layers: 1
  embedding_dim: 50
  MLP_hidden: 500
  MLP_num_layers: 2
  heads: 4
  aggregate: 'mean'
  normalization: 'ln'
  deepset_input_norm: True
  deepset_input_norm: True
  GPR: False
  PMA: True
  lr: 0.001
  wd: 0.0
